### ISSUE TITLE
Is Veronica alive?

### ISSUE THREAD

**Issue by alundiak** [cyle/cylebot#1]
Being here http://cylesoft.com/veronica/  and providing text inputs I see errors in console.log:

```
 Uncaught TypeError: undefined is not a function
veronica.js:79 deal_with_input
```

It's about:

```
 history.push(i);
```

Tested on Chrome/Windows.

**Comment by cyle** [comment]
Fixed. See [this commit](https://github.com/cyle/veronica/commit/32843c88124ab50764e3df62eec201328522ef7a). Apparently `history` is a special javascript keyword in chrome all of a sudden. 

Thanks for pointing it out! Haven't been able to play with this in awhile.
